server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: fornecedor
  cloud:
    config:
      uri: http://localhost:8888/
  config:
    import:
      config-server:

  #datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: postgres
    password: admin

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

